RMDIR /S /Q "Win32\launcher_d"
RMDIR /S /Q "Win32\zeniapp_d"
RMDIR /S /Q "Win32\zenilib_d"
RMDIR /S /Q "x64\launcher_d"
RMDIR /S /Q "x64\zeniapp_d"
RMDIR /S /Q "x64\zenilib_d"

DEL /Q "..\bin\*_d.exe"
DEL /Q "..\bin\x64\*_x64d.exe"
DEL /Q "..\*_d.exe"
DEL /Q "..\*_x64d.exe"
