RMDIR /S /Q "Win32\launcher_d"
RMDIR /S /Q "Win32\zeniapp_d"
RMDIR /S /Q "Win32\zenilib_d"
RMDIR /S /Q "x64\launcher_d"
RMDIR /S /Q "x64\zeniapp_d"
RMDIR /S /Q "x64\zenilib_d"

DEL /Q "..\Launch_Zeniapp_d.exe"
DEL /Q "..\bin\Zeniapp_d.exe"
DEL /Q "..\Launch_Zeniapp_x64d.exe"
DEL /Q "..\bin\x64\Zeniapp_x64d.exe"
